@startuml
!include ../../../../style_puml.config

participant "Browser" as bro
participant "Trusona SDK" as sdk
participant "Customer Backend" as cust
participant "Trusona Auth Cloud" as core

bro -> sdk: authenticate (optional user hint)
sdk -> core: POST /fido2/assertion/options
core --> sdk: JWT
sdk --> bro: (idToken, accessToken)
bro -> sdk: get Initializer.jwksEndpoint
sdk --> bro: jwks_endpoint
bro -> cust: verify accessToken with jwks_endpoint
cust -> core: GET /jwks_endpoint
core --> cust: jwks
cust -> cust: verify accessToken with jwks
cust --> bro: verification success
bro -> cust: access with accessToken

@enduml