@startuml
!include ../../../../style_puml.config

participant "Browser" as bro
participant "Trusona SDK" as sdk
participant "Customer Backend" as cust
participant "Trusona Auth Cloud" as core

bro -> cust: Sign in using existing authentication method
cust --> bro: Success
bro -> sdk: enroll with JWT
sdk -> core: POST /api/v1/attestation/options (JWT)
core -> cust: GET /somepath/jwks
cust --> core: jwks 
core -> core: Validate JWT with jwks
core --> sdk: attestation_options, transaction_id
sdk -> bro: create webauthn credentials using attestation_options
bro --> sdk: attestation_options
sdk -> core: POST /api/v1/attestation/registrations (attestation_options, transaction_id)
core -> core: create passkey credential
core --> sdk: enrollment result
sdk --> bro: enrollment result

@enduml